### ISSUE TITLE
check_firmware_pwd always returns True

### ISSUE THREAD

**Issue by SynAckJack** [SynAckJack/dotfiles#1]
For some reason the check_firmware_pwd functions always returns True.

- Tried changing `grep -q 'Yes'` to `No`
- When testing command in Terminal it works fine

```
function check_firmware_pwd {

	if firmwarepasswd -check | grep -q 'Yes' ; then
		return 0
	else
		return 1
	fi
}
```

Example output of running command in terminal (when password not enabled):

```
sudo firmwarepasswd -check
Password Enabled: No
```

**Comment by SynAckJack** [comment]
Tried changing if-statement condition to `sudo bash -c "firmwarepasswd -check | grep -q 'Yes'"` in case it was an issue with the command having to be run as sudo. This didn't solve the issue.

**Comment by 0xmachos** [comment]
`firmwarepasswd ` does need to be run with `sudo`. 

You had the format right in your [first comment](https://github.com/SynAckJack/dotfiles/issues/1#issue-347203008) just add `sudo`: 

```
if sudo firmwarepasswd -check | grep -q 'Yes'; then
  return 0
else
  return 1
fi
```

I think the issue lies in your `audit_macOS` function. 

The code that iterates through the  `audit_functions` array and calling each function ([lines 134-140](https://github.com/SynAckJack/dotfiles/blob/master/coffee.sh#L134-L140)):
```
for f in "${audit_functions[@]}" ; do
  if [[ "${f}" ]] ; then
    AUDIT_PASS+=("${f}")
  else
    AUDIT_FAIL+=("${f}")
  fi
done
```

I think [line 135](https://github.com/SynAckJack/dotfiles/blob/master/coffee.sh#L135):

```
if [[ "${f}" ]] ; then
```

Should be:

```
if "${f}";  then
```

**Comment by SynAckJack** [comment]
Issue now fixed from above comment.

Thanks  😃
